service:
  type: NodePort
  port: 80
image:
  repository: petitbou/datascientestapi # replace this yourdocker_hub_id/datascientestapi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
serviceAccount:
  create: true
